# Basic
title: Wons' Blog
subtitle: 个人博客
welcome_message: 回首向来萧瑟处，也无风雨也无晴
description: 后端程序猿 - Python / C++ / Java
creator: <a href="http://lwons.com">Wons Liu</a>

url: "http://blog.lwons.com"

permalink: /archieve/:title.html

# Format
markdown: kramdown
kramdown:
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

nav:
    - {title: About, description: About Me, url: '/archieve/about_me.html'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Social
social:
    weibo: liuwons
    github: liuwons
    mail: a@lwons.com
    csdn: tobacco5648

baidu_analyze_id: 223c8334613f17de83d2430fd15a79d6
