# Site settings
name: Wons Liu
description: "Hello World"
url: ""


github_username:  "liuwons"
facebook_username: "liuwons"
stack_of_username: "liuwons"
weibo_username: "liuwons"
blog_url: "/blog"
email: "a@lwons.com"


avatar: yes
avatar_img_path: "imgs/profile.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"

# Build settings
#markdown: kramdown
#permalink: pretty

##################

title: Wons Liu

permalink: /blog/:title.html
timezone: Asia/Shanghai

safe: true
lsi: false
markdown: kramdown
kramdown:
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil
# Keybase
include:
  - .well-known

gems:
  - jekyll-sitemap
