# Site settings
name: Wons Liu
description: "Hello World"
url: ""


github_username:  "liuwons"
facebook_username: "liuwons"
stack_of_username: "liuwons"
weibo_username: "liuwons"
blog_url: "/blog"
email: "a@lwons.com"


avatar: yes
avatar_img_path: "imgs/profile.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"

# Build settings
#markdown: kramdown
#permalink: pretty






##################




title: Yong Yuan

# 自定义post url
permalink: /blog/:title.html
timezone: Asia/Shanghai

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false
#markdown: kramdown
#kramdown:
#  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
#    extensions:
#    - autolink
#    - footnotes
#    - smart
#  use_coderay: true
#  syntax_highlighter: rouge
#  coderay:
#    coderay_line_numbers:  nil
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "underline"]

# Keybase
include:
  - .well-known

# White-listed plugins
gems:
  - jekyll-sitemap