# Site settings
name: Wons Liu
description: "Hello World"
url: ""


github_username:  "liuwons"
facebook_username: "liuwons"
stack_of_username: "liuwons"
weibo_username: "liuwons"
blog_url: "/blog"
email: "a@lwons.com"


avatar: yes
avatar_img_path: "imgs/profile.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"

# Build settings
#markdown: kramdown
#permalink: pretty
